### ISSUE TITLE
TypeError: HPSv2.__init_subclass__() takes no keyword arguments

### ISSUE THREAD

**Issue by Keyu-Yan** [RE-N-Y/imscore#2]
When I use hpsv2 

`from imscore.hps.model import HPSv2`

I meet this err:

`TypeError: HPSv2.__init_subclass__() takes no keyword arguments`

**Comment by RE-N-Y** [comment]
Could you share the full code? Is it coming from import statement?

You should init the model like this:
```python
model = HPSv2.from_pretrained("RE-N-Y/hpsv21") # HPSv2.1 preference scorer
```

but I will check on my end as well

**Comment by RE-N-Y** [comment]
I've tested the package in a separate colab environment and could not replicate the issue. Feel free to re-open with full code attached if problem still persists.
