### ISSUE TITLE
Have you tested the performance on the original dataset?

### ISSUE THREAD

**Issue by LinB203** [RE-N-Y/imscore#3]
Great work! Have you tested the performance on the original dataset with this library? Having a baseline performance would increase confidence in its use.

**Comment by LinB203** [comment]
Apologies for my impatience; we have several text-to-image models to evaluate and would be glad to serve as one of the first testers for this project.

**Comment by RE-N-Y** [comment]
@LinB203 thanks for asking! In the README.md, there is a benchmark table of results on original datasets.
Is there a specific set of results you're looking for?

HPSv21, MPS, Pickscore, LAION Aesthetic scorer are ported over from existing models.

**Comment by LinB203** [comment]
> @LinB203 thanks for asking! In the README.md, there is a benchmark table of results on original datasets. Is there a specific set of results you're looking for?
> 
> HPSv21, MPS, Pickscore, LAION Aesthetic scorer are ported over from existing models.

Thank you for your response. Please forgive me for continuing to bother you, I have a few more questions I would like to clarify further.


1. I would like to confirm whether HPSv21, MPS, Pickscore, and LAION Aesthetic are models transferred from the official versions. 
2. Is LAION Aesthetic v1 or v2?
3. The performance of ImageReward mentioned in the readme is based on your own retrained model rather than one transferred from the official version, right? If so, what does the "performance" of ImageReward refer to?

**Comment by LinB203** [comment]
Thank you for your reply!

**Comment by LinB203** [comment]
Two weeks is acceptable for me since I am currently testing some other benchmarks. If you could put the evaluation results with the discrepancy in the README, it would make it more acceptable for others to use. Thank you again for your hard work.

**Comment by RE-N-Y** [comment]
@LinB203 Quick update on the progress.
I'm going to be putting out a fix this weekend which fixes the discrepancy between original model / ported implementation.
I've implemented a fix for Pickscore, HPSv21, and MPS. I still need to fix LAION Aesthetic v2 scorer, but will keep you posted on discrepancy and evaluation results.

I'm hoping to get the fixes and evals as part of a new release over this weekend.

**Comment by RE-N-Y** [comment]
Added discrepancies in the README, with the new 0.0.4 release, more evals are coming soon.

**Comment by RE-N-Y** [comment]
@LinB203
1. Discrepancy results have been added to README
2. Full benchmarks on original preference dataset has been added to README and bench.md
3. Also, added ImageReward with 0.0.5 release.

Let me know if you have questions!

**Comment by LinB203** [comment]
Great, thanks for all your hard work, I'm enjoying the project!

**Comment by LinB203** [comment]
Over this past time I've noticed that the model's dense caption is now generally larger than the maximum length of the clip/blip, so perhaps these human preference models are largely biased towards aesthetic assessment. Therefore I felt the need to include VQAScore.

**Comment by RE-N-Y** [comment]
@LinB203 Closing issue since performance and discrepancy table has been added.
I will create a separate issue for VQAScore to track that separately.
